In [ ]:

Open In Colab
Lists
In [20]:
first = [82,58,42,12,'marks','flat','chess']
first
Out[20]:
[82, 58, 42, 12, 'marks', 'flat', 'chess']
In [21]:
first.append('fog')
first
Out[21]:
[82, 58, 42, 12, 'marks', 'flat', 'chess', 'fog']
In [22]:
first.index(12)
Out[22]:
3
In [34]:
first.insert(3,888)
first
Out[34]:
[82, 58, 42, 888, 12, 'marks', 'flat', 'chess', 'fog']
In [29]:
lst = [14,22,56,38,82,68,97]
lst.sort()
lst
Out[29]:
[14, 22, 38, 56, 68, 82, 97]
In [30]:
lst.reverse()
lst
Out[30]:
[97, 82, 68, 56, 38, 22, 14]
In [35]:
first.extend(lst)
first
Out[35]:
[82,
 58,
 42,
 888,
 12,
 'marks',
 'flat',
 'chess',
 'fog',
 97,
 82,
 68,
 56,
 38,
 22,
 14]
In [47]:
first.copy()
Out[47]:
[82,
 58,
 42,
 888,
 12,
 'marks',
 'flat',
 'chess',
 'fog',
 97,
 82,
 68,
 56,
 38,
 22,
 14]
In [36]:
lst.remove(97)
lst
Out[36]:
[82, 68, 56, 38, 22, 14]
In [37]:
lst.pop()
Out[37]:
14
In [38]:
lst.pop(2)
Out[38]:
56
In [45]:
lenclear()
Out[45]:
0
Dictionary
In [49]:
dit = {'name':'Ankush','class':10,'section':'A','number':999999999,'fav_colour':'blue',}
dit
Out[49]:
{'class': 10,
 'fav_colour': 'blue',
 'name': 'Ankush',
 'number': 999999999,
 'section': 'A'}
In [50]:
del dit['fav_colour']
dit
Out[50]:
{'class': 10, 'name': 'Ankush', 'number': 999999999, 'section': 'A'}
In [51]:
dit.items()
Out[51]:
dict_items([('name', 'Ankush'), ('class', 10), ('section', 'A'), ('number', 999999999)])
In [52]:
dit.pop('name')
Out[52]:
'Ankush'
In [54]:
dit.values()
Out[54]:
dict_values([10, 'A', 999999999])
In [55]:
dit.get('class')
Out[55]:
10
In [58]:
dit.clear()
dit
Out[58]:
{}
Sets
In [60]:
a = {1,2,3,3,3,5,8,8,7,9,8}
b = {4,6,6,3,2,7,7}
Out[60]:
{1, 2, 3, 5, 7, 8, 9}
In [62]:
a.pop()
Out[62]:
1
In [63]:
a.intersection(b)
Out[63]:
{2, 3, 7}
In [64]:
a.union(b)
Out[64]:
{2, 3, 4, 5, 6, 7, 8, 9}
In [65]:
a.difference(b)
Out[65]:
{5, 8, 9}
In [67]:
a.clear()
a
Out[67]:
set()
Tuples
In [75]:
T = ('Ram','Sid',26,11,58,26,14.7)
T
Out[75]:
('Ram', 'Sid', 26, 11, 58, 26, 14.7)
In [76]:
len(T)
Out[76]:
7
In [77]:
T.index(58)
Out[77]:
4
In [78]:
T.count(26)
Out[78]:
2
Strings
In [81]:
ST = "Mumbai Indians will win IPL in 2020"
ST
Out[81]:
'Mumbai Indians will win IPL in 2020'
In [82]:
ST.islower()
Out[82]:
False
In [83]:
ST.lower()
Out[83]:
'mumbai indians will win ipl in 2020'
In [84]:
ST.upper()
Out[84]:
'MUMBAI INDIANS WILL WIN IPL IN 2020'
In [86]:
ST.count('w')
Out[86]:
2
In [88]:
ST.find('win')
Out[88]:
20